"""empty message

Revision ID: 214cc161e6a2
Revises: 6eeb184dd80c
Create Date: 2025-04-05 20:23:24.606922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214cc161e6a2'
down_revision = '6eeb184dd80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('description', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment', 'description')
    # ### end Alembic commands ###
