"""empty message

Revision ID: 7e8b907a4406
Revises: e92fb37c422c
Create Date: 2025-04-05 22:34:43.252522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8b907a4406'
down_revision = 'e92fb37c422c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('creator', sa.String(length=11), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('mender', sa.String(length=11), nullable=False),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module')
    # ### end Alembic commands ###
