"""empty message

Revision ID: 994043b71d3e
Revises: 214cc161e6a2
Create Date: 2025-04-05 21:18:59.102895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994043b71d3e'
down_revision = '214cc161e6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('creator', sa.String(length=11), nullable=False))
    op.add_column('environment', sa.Column('add_time', sa.DateTime(), nullable=True))
    op.add_column('environment', sa.Column('mender', sa.String(length=11), nullable=False))
    op.add_column('environment', sa.Column('edit_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'environment', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'environment', type_='unique')
    op.drop_column('environment', 'edit_time')
    op.drop_column('environment', 'mender')
    op.drop_column('environment', 'add_time')
    op.drop_column('environment', 'creator')
    # ### end Alembic commands ###
