"""empty message

Revision ID: e92fb37c422c
Revises: 994043b71d3e
Create Date: 2025-04-05 21:20:39.572752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92fb37c422c'
down_revision = '994043b71d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment', 'is_default')
    # ### end Alembic commands ###
