apiVersion: apps/v1
kind: Deployment
metadata:
  name: qatool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qatool
  template:
    metadata:
      labels:
        app: qatool
    spec:
      containers:
      - name: kubefox
        image: wzj751127122/qatool:build-5
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: qatool
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: qatool